import type { Metadata } from "next";
import "./globals.css";
import { MobileHeader, DesktopSidebar } from "../components/Sidebar";
import { Providers } from "../components/Providers";

export const metadata: Metadata = {
  title: "402 dispute resolution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-800">
        <Providers>
          <div className="max-w-7xl mx-auto w-full">
            <MobileHeader />
            <div className="flex">
              <DesktopSidebar />
              <main className="flex-1">{children}</main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
